# Generated by Django 6.0 on 2025-12-13 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_batch_department_classsection_facultyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='core.studentprofile')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classsection')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_teams', to='core.facultyprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='core.studentprofile')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_teams', to='core.facultyprofile')),
                ('team_leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='leading_team', to='core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('objectives', models.TextField()),
                ('domain', models.CharField(max_length=200)),
                ('expected_outcomes', models.TextField()),
                ('estimated_duration_weeks', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REVISION', 'Revision Required'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('coordinator_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_projects', to='core.facultyprofile')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
